### ISSUE TITLE
Is it possible to create agents in that way? 

### ISSUE THREAD

**Issue by maxbaluev** [TypeAI-dev/typeai#1]

**Comment by jefflaporte** [comment]
Hi @maxbaluev 

There isn't currently any functionality that directly targets agent creation, but I can tell you that I am also interested in building agents and started building TypeAI as a first step.

To add it bit more context, my own reason for wanting this functionality is to move up a layer. Once generating models and functions becomes trivial, it becomes cheap (in an engineering sense) to define AI capabilities rapidly, and tie them together in larger patterns (beyond chaining…). So I do want to head in this direction but want to experiment with how to express each layer in turn. For example, I'd like to make it fairly easy to opt-in to higher level patterns like tree-of thought. 

Baby steps at the moment but I do view this as in-scope for TypeAI.
