### ISSUE TITLE
Loading OpenAI API Key

### ISSUE THREAD

**Issue by khill-fbmc** [TypeAI-dev/typeai#6]
I am not sure where you want it to show in the README, but I think it would be helpful to include a note stating we (consumers) need to have `OPENAI_API_KEY` defined as an environment variable at runtime. It took me a minute to deduce that from investigation since I thought the lib was doing the extra lifting for me behind the scenes.

This is my preferred method of an ephemeral run of a TS file:
```sh
npx dotenv-cli -e .env tsx index.ts
```

Another alternative would be to include an exported method that would allow a user to pass in their key.

What are your thoughts?

**Comment by khill-fbmc** [comment]
Noting here that in issue #4, you discovered `tsx` [doesn't work with deepkit](https://github.com/TypeAI-dev/typeai/issues/4#issuecomment-1679689345)

**Comment by jefflaporte** [comment]
@khill-fbmc I've added both these items to the installation section of the readme 👍
